name: 'Upload to Estuary.tech'
description: 'Upload your website or repository to Estuary.tech'
author: 'Kelindi'
branding:
  icon: 'box'
  color: 'white'
inputs:
  access_token:
    description: 'Access Token for API Endpoint'
    required: true
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: False
  pin_name:
    description: 'Name of pin'
    required: false
outputs:
  cid:
    description: 'IPFS Content ID of the pinned file/directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACCESS_TOKEN: ${{ inputs.access_token }}
    UPLOAD_PATH: ${{ inputs.path_to_add }}
    NAME: "${{ env.github.repository }}-${{ env.github.event.repository.updated_at}}"
  
